### ISSUE TITLE
Any intention of publishing to crates.io?

### ISSUE THREAD

**Issue by bonsairobo** [khonsulabs/lrumap#2]
This crate seems nice, but is it still being used by anyone else? I'd prefer to use this over the more popular `lru` crate using a lot of unsafe.

**Comment by ecton** [comment]
Yes! It's been on my list to take across the finish line. I was originally waiting to publish after I had used it where I was planning on using it, but I ended up not using it in any published project yet.

Knowing there's other people interested, I'll get this done sooner rather than later!

**Comment by ecton** [comment]
I've published [v0.1.0](https://crates.io/crates/lrumap/0.1.0). I'm confident there will be some rough edges -- if you notice any missing functionality or encounter any confusing design decisions I made, please let me know!
